DROP TABLE IF EXISTS Accidents CASCADE;
DROP TABLE IF EXISTS Location CASCADE;
DROP TABLE IF EXISTS Severity CASCADE;
DROP TABLE IF EXISTS Environment CASCADE;
DROP TABLE IF EXISTS Parties CASCADE;
DROP TABLE IF EXISTS Victims CASCADE;

-- Create Location table
CREATE TABLE Location (
    LOCATION_ID SERIAL PRIMARY KEY,
    PRIMARY_RD VARCHAR(50),
    SECONDARY_RD VARCHAR(50),
    DISTANCE NUMERIC,
    DIRECTION CHAR(1),
    INTERSECTION CHAR(1),
    LATITUDE DOUBLE PRECISION,
    LONGITUDE DOUBLE PRECISION,
    CITY VARCHAR(30),
    COUNTY VARCHAR(30),
    POINT_X DOUBLE PRECISION,
    POINT_Y DOUBLE PRECISION
);

-- Create Severity table
CREATE TABLE Severity (
    SEVERITY_ID SERIAL PRIMARY KEY,
    COLLISION_SEVERITY CHAR(1),
    NUMBER_KILLED INT,
    NUMBER_INJURED INT,
    COUNT_SEVERE_INJ INT,
    COUNT_VISIBLE_INJ INT,
    COUNT_COMPLAINT_PAIN INT,
    COUNT_PED_KILLED INT,
    COUNT_PED_INJURED INT,
    COUNT_BICYCLIST_KILLED INT,
    COUNT_BICYCLIST_INJURED INT,
    COUNT_MC_KILLED INT,
    COUNT_MC_INJURED INT
);

-- Create Environment table
CREATE TABLE Environment (
    ENVIRONMENT_ID SERIAL PRIMARY KEY,
    WEATHER_1 CHAR(1),
    WEATHER_2 CHAR(1),
    ROAD_SURFACE CHAR(1),
    ROAD_COND_1 CHAR(1),
    ROAD_COND_2 CHAR(1),
    LIGHTING CHAR(1),
    STATE_HWY_IND CHAR(1)
);

-- Create Accidents table with CHAR(1) fields for Boolean-like data
CREATE TABLE Accidents (
    CASE_ID SERIAL PRIMARY KEY,
    ACCIDENT_YEAR INT,
    COLLISION_DATE DATE,
    COLLISION_TIME TIME,
    LOCATION_ID INT REFERENCES Location(LOCATION_ID),
    SEVERITY_ID INT REFERENCES Severity(SEVERITY_ID),
    ENVIRONMENT_ID INT REFERENCES Environment(ENVIRONMENT_ID),
    PARTY_COUNT INT,
    HIT_AND_RUN CHAR(1),
    TYPE_OF_COLLISION CHAR(1),
    PEDESTRIAN_ACCIDENT CHAR(1),
    BICYCLE_ACCIDENT CHAR(1),
    MOTORCYCLE_ACCIDENT CHAR(1),
    TRUCK_ACCIDENT CHAR(1),
    MVIW CHAR(1),
    ALCOHOL_INVOLVED CHAR(1),
	PCF_VIOL_CATEGORY CHAR(2),
	DAY_OF_WEEK CHAR(1)
);

-- Create Parties table
CREATE TABLE Parties (
    PARTY_ID SERIAL PRIMARY KEY,
    CASE_ID INT REFERENCES Accidents(CASE_ID),
    PARTY_NUMBER INT,
    PARTY_TYPE CHAR(1),
    AT_FAULT CHAR(1),
    PARTY_SEX CHAR(1),
    PARTY_AGE INT,
    PARTY_SOBRIETY CHAR(1),
    PARTY_DRUG_PHYSICAL CHAR(1),
    DIR_OF_TRAVEL CHAR(1),
    PARTY_SAFETY_EQUIP_1 CHAR(1),
    PARTY_SAFETY_EQUIP_2 CHAR(1),
    FINAN_RESPONS CHAR(1),
    VEHICLE_YEAR INT,
    VEHICLE_MAKE VARCHAR(50),
    STWD_VEHICLE_TYPE CHAR(1),
	INATTENTION CHAR(1),
    RACE CHAR(1),
	MOVE_PRE_ACC CHAR(1)
);

-- Create Victims table
CREATE TABLE Victims (
    VICTIM_ID SERIAL PRIMARY KEY,
    CASE_ID INT REFERENCES Accidents(CASE_ID),
    PARTY_ID INT REFERENCES Parties(PARTY_ID),
    VICTIM_ROLE CHAR(1),
    VICTIM_SEX CHAR(1),
    VICTIM_AGE INT,
    VICTIM_DEGREE_OF_INJURY CHAR(1),
    VICTIM_SEATING_POSITION CHAR(1),
    VICTIM_SAFETY_EQUIP_1 CHAR(1),
    VICTIM_SAFETY_EQUIP_2 CHAR(1),
    VICTIM_EJECTED CHAR(1)
);
